variables:
  IMAGE_NAME: manhhoach/sound-flute
  IMAGE_TAG: nodejs

stages:
  - build
  - deploy


.build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA

build-dev:
  extends: .build
  only:
    - master
deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@54.163.67.48 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        lsof -i :5000 &&
        docker run -p 5000:5000 -d $IMAGE_NAME:$CI_COMMIT_SHA"

