version: '3'
services:
  sound-flute:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_IMAGENAME}
    environment:
      DATABASE: ${DATABASE}
      cloud_name: ${cloud_name}
      api_key: ${api_key}
      api_secret: ${api_secret}
    ports: 
      - 5000:5000
    restart: always
    volumes:
      - /app/node_modules
      - .:/app